services:
  node:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_crud1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  db-data: {}
